### PR TITLE
feat: add contents of how to run autoware on xavier platform

### PR DESCRIPTION
**Pull request by cyn-liu**
Signed-off-by: Cynthia Liu <cynthia.liu@autocore.ai>

Add contents of how to run autoware on xavier platform.
The contents include getting-started-xavier and system-setup-xavier.
The contents add in version 2.0.

### CODE REVIEW

**Comment by liuXinGangChina** [comment]
Hi, @kenji-miyake . Please assign a reviewer for this pr.

Thanks!

**Comment by kenji-miyake** [comment]
@liuXinGangChina @cyn-liu Sure! But I think it's good to consider becoming members of https://github.com/orgs/autowarefoundation/teams/autoware-developers so that AutoCore members can set reviewers by yourself.
Please ask Bonolo-san for that.

**Comment by kenji-miyake** [comment]
@d-hashimoto @ito-san Who do you think are appropriate reviewers? I'm not familiar with this repository. For now, please let me set you two as reviewers. :bow:

**Comment by liuXinGangChina** [comment]
> 

Hi, @kenji-miyake .Thanks for your kindly help. I will contact Bonolo-san for further detail related to join autoware-developer.

**Comment by liuXinGangChina** [comment]
Hi, Miyake-san @kenji-miyake .Since this pr is just about “How to guide”， and we have done field test with jetson xavier，can you consider merging it. Then we can create prs about other arm-based platform, like pcu and jetson orin.

**Comment by kenji-miyake** [comment]
@liuXinGangChina We're sorry about that. I'll merge this.
I think it's okay for AutoCore to maintain this docs site.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
