### PR TITLE
chore: fix emoji not emoji not rendered

### PR DESCRIPTION
**Pull request by ito-san**
Signed-off-by: ito-san <fumihito.ito@tier4.jp>

Emojis are not rendered on GItHub pages.
image

After this fix.
image

### CODE REVIEW

**Comment by ghost** [comment]
@ito-san Could you fix the warnings in the github action "spell-check-differential" and dead links "pre-commit-optional"?

**Comment by ito-san** [comment]
@d-hashimoto 

> @ito-san Could you fix the warnings in the github action "spell-check-differential" and dead links "pre-commit-optional"?

OK! Let me file another PR to fix this.

**Review by ghost — APPROVED** [review]

**Comment by ito-san** [comment]
@d-hashimoto

> > Could you fix the warnings in the github action "spell-check-differential" and dead links "pre-commit-optional"?
>
> OK! Let me file another PR to fix this.

This has been fixed in https://github.com/autowarefoundation/open-ad-kit-docs/pull/33.

**Comment by ghost** [comment]
@ito-san I reviewed https://github.com/autowarefoundation/open-ad-kit-docs/pull/33 , and approved it. Thank you!

**Pull request merged**
