### PR TITLE
feat: add v1 contents of how to run autoware and simulators

### PR DESCRIPTION
**Pull request by ghost**
Adding the contents for version 1.0 in the "How to run autoware" and "How to run simulators".

This contents was diverted from [the version 1.0 document](https://gitlab.com/autowarefoundation/autoware_reference_design) and I revised them to adjust for the current document structure.

Signed-off-by: Daisuke Hashimoto <daisuke.hashimoto@tier4.jp>

### CODE REVIEW

**Comment by ghost** [comment]
@LalithVipulananthan The github action, "pre-commit-optional", shows a dead link of [https://account.tier4.jp/](https://account.tier4.jp/), but the link works.

**Comment by ghost** [comment]
> @LalithVipulananthan The github action, "pre-commit-optional", shows a dead link of https://account.tier4.jp/, but the link works.

This happened last time as well. I wonder if the firewall protecting the account.tier4.jp page is blocking incoming requests from the CI/CD server? 🤔 

@kenji-miyake I am guessing that none of the current AW documentation pages refer to the account.tier4.jp page, but is there any chance that you've seen this problem before? Although this is an optional check and we can just ignore any failures, it would be good if we could resolve the failure. 🙂

**Comment by kenji-miyake** [comment]
You can add ignore patterns to `markdown-link-check.json`.

Then, you have to remove this sync setting.
https://github.com/autowarefoundation/open-ad-kit-docs/blob/a84f898aaead1cb79e4640d6f3925955c41e5f66/.github/sync-files.yaml#L17

Or please add `pre-commands` like the following.

```yaml
    - source: .markdown-link-check.json
      pre-commands: |
        sd -s -- \
        '     "pattern": "^http://localhost"' \
        '     "pattern": "^https://account.tier4.jp/"
            },
            {
              "pattern": "^http://localhost"' \
          {source}
```

**Comment by ghost** [comment]
@kenji-miyake Thank you so much, and it works well!!

**Review by NaoyoriTanzawa — APPROVED** [review]

**Pull request merged**
