### PR TITLE
feat: add contents of the application example chapter

### PR DESCRIPTION
**Pull request by ghost**
Adding contents of the Application Example chapter to provide the baseline for documenting the reference design for the Bus ODD.  I imported contents from [the version 1.0 document repo](https://gitlab.com/autowarefoundation/autoware_reference_design/-/tree/main/docs), and added ConOps and OpsCon chapters for adjusting to the latest status.

Signed-off-by: Daisuke Hashimoto <daisuke.hashimoto@tier4.jp>

### CODE REVIEW

**Comment by ghost** [comment]
@NaoyoriTanzawa I added the contents of ConOps and OpsCons. If you have a time, please refer to  https://autowarefoundation.github.io/open-ad-kit-docs/pr-21/

**Comment by ghost** [comment]
@d-hashimoto Thank you for your work on this. Can I request that future PRs are kept small to make reviewing easier? This PR now has 91 modified files, and so reviewing this PR will be quite challenging. 😢 

On a different note, may I ask why concepts (eg: Autoware Core/Universe, Autoware APIs) are being included in the driverless bus section? My understanding is that this information would be the same for all application examples (driverless bus, robotaxi etc) and so should either be added at a higher level of the docs. Alternatively, we should add this information to the main Autoware docs and then reference them here.

**Review by NaoyoriTanzawa — APPROVED** [review]

**Comment by NaoyoriTanzawa** [comment]
@d-hashimoto @LalithVipulananthan Although I just reviewed the contents, bus ConOps/OpsCon part could be separated from open-ad-kit-docs. This is because the current Open AD Kit (1.0/2.0) is not related with Bus use cases directly.

**Comment by ghost** [comment]
@LalithVipulananthan I am sorry for the large PR. I'll create smaller PRs.

> On a different note, may I ask why concepts (eg: Autoware Core/Universe, Autoware APIs) are being included in the driverless bus section? My understanding is that this information would be the same for all application examples (driverless bus, robotaxi etc) and so should either be added at a higher level of the docs. Alternatively, we should add this information to the main Autoware docs and then reference them here.

I just imported the Software Requirements chapter from the old repository. As you mentioned, the position of the common contents, like Autoware APIs, should be in a higher level.
I'll create another PR to solve this issue.

**Comment by ghost** [comment]
> @d-hashimoto @LalithVipulananthan Although I just reviewed the contents, bus ConOps/OpsCon part could be separated from open-ad-kit-docs. This is because the current Open AD Kit (1.0/2.0) is not related with Bus use cases directly.

@NaoyoriTanzawa Oh... In this case, I think the contents for the ConOps&OpsCons chapters should be the MIH demo's ConOps&OpsCons. I'll change the contents of that in other PRs.

**Pull request merged**
